kind: Service
apiVersion: v1
metadata:
  name: $name
  labels:
    name: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    name: postgres
  portalIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
