kind: Service
apiVersion: v1
metadata:
  name: $service
  labels:
    name: postgresql
spec:
  ports:
    - protocol: TCP
      port: $hostPort
      targetPort: 5432
      nodePort: 0
  selector:
    name: postgresql
  portalIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
